// const fs = require('fs')
// fs.writeFileSync('notes.txt', 'My Name is Abhijeet Kulshreshtha')
// fs.appendFileSync('notes.txt', '. I live in Bangalore')

// const add = require('./utils.js')
// const sum = add(4, 5)
// console.log(sum)
const validator=require('validator')
const chalk=require('chalk')
const getNotes = require('./notes.js')
console.log(chalk.yellow.bold.inverse(getNotes()))
console.log(chalk.red(validator.isEmail('abhijeet.abap%cbc.com')))
console.log(chalk.blue.bold(validator.isURL('www.sap.com')))